name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Optional version tag for the image (e.g., v1.2.3)'
        required: false
        default: ''

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t url-shortener .

    - name: Tag Docker image as latest
      run: docker tag url-shortener elainehiseh/url-shorten:latest

    - name: Push latest tag
      run: docker push elainehiseh/url-shorten:latest

    - name: Tag and push versioned image (if provided)
      if: ${{ github.event.inputs.version != '' }}
      run: |
        docker tag url-shortener elainehiseh/url-shorten:${{ github.event.inputs.version }}
        docker push elainehiseh/url-shorten:${{ github.event.inputs.version }}
